package main

// Code generated by BarefootJS for the net/http adapter. DO NOT EDIT.
// To refresh, delete this file and re-run `bf init` from a fresh
// directory — `bf init` skips existing files, so it won't clobber your
// edits in place.

import (
	"fmt"
	"html/template"
	"io/fs"
	"net/http"
	"os"
	"path/filepath"
	"strings"

	bf "github.com/barefootjs/runtime/bf"
	"github.com/barefootjs/runtime/bf/bfdev"
)

// loadTemplates walks dist/templates/ recursively and parses every
// .tmpl file. ParseGlob("dist/templates/*.tmpl") only catches the
// top-level directory, missing per-component subdirectories like
// dist/templates/ui/button/index.tmpl that a parent invokes via
// {{template "Button" ...}}.
//
// Also registers a no-op "Tag" template so html/template's escape pass
// (which validates references in unreachable branches too) doesn't
// crash the first call to any template that transitively includes Slot
// — the go-template adapter emits a {{template "Tag" ...}} reference
// inside Slot that's only reachable when AsChild=true.
func loadTemplates() (*template.Template, error) {
	root := template.New("").Funcs(bf.FuncMap())
	root = root.Funcs(bf.TemplateFuncMap(root))
	if _, err := root.New("Tag").Parse(""); err != nil {
		return nil, err
	}
	err := filepath.WalkDir("dist/templates", func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || filepath.Ext(path) != ".tmpl" {
			return nil
		}
		_, parseErr := root.ParseFiles(path)
		return parseErr
	})
	return root, err
}

// layoutWithDev wraps the user's defaultLayout (renderer.go) with the
// dev auto-reload snippet, injected just before </body>. In production
// (APP_ENV=production) the snippet is empty and the layout passes
// through unchanged.
func layoutWithDev(ctx *bf.RenderContext) string {
	html := defaultLayout(ctx)
	snippet := bfdev.Snippet(bfdev.Config{Disabled: !IsDev()})
	if snippet == "" {
		return html
	}
	return strings.Replace(html, "</body>", string(snippet)+"\n</body>", 1)
}

// mustNewRenderer loads templates once at startup and pairs them with
// layoutWithDev. On parse failure we surface the cause to stderr and
// exit non-zero, so the cause shows up before the Go panic stack trace.
func mustNewRenderer() *bf.Renderer {
	tmpl, err := loadTemplates()
	if err != nil {
		fmt.Fprintf(os.Stderr, "barefoot: failed to load templates from dist/templates: %v\n", err)
		fmt.Fprintln(os.Stderr, "barefoot: did you run `vite build` first?")
		os.Exit(1)
	}
	return bf.NewRenderer(tmpl, layoutWithDev)
}

// renderToString renders a component to a full HTML page. In dev mode
// templates are re-parsed on every call so a `vite dev` update
// surfaces as soon as the browser refreshes — no Go restart needed. In
// production the parse happens once (renderer is reused).
func renderToString(renderer *bf.Renderer, name string, opts bf.RenderOptions) (string, error) {
	r := renderer
	if IsDev() {
		tmpl, err := loadTemplates()
		if err != nil {
			return "", err
		}
		r = bf.NewRenderer(tmpl, layoutWithDev)
	}
	opts.ComponentName = name
	return r.Render(opts), nil
}

// render writes a fully laid-out HTML page for the named component.
func render(w http.ResponseWriter, renderer *bf.Renderer, status int, name string, opts bf.RenderOptions) {
	html, err := renderToString(renderer, name, opts)
	if err != nil {
		http.Error(w, fmt.Sprintf("template error: %v", err), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.WriteHeader(status)
	_, _ = w.Write([]byte(html))
}

// MountDevReload registers the SSE auto-reload endpoint in dev mode.
// In production it is a no-op.
func MountDevReload(mux *http.ServeMux) {
	if !IsDev() {
		return
	}
	mux.Handle("/_bf/reload", bfdev.NewReloadHandler(bfdev.Config{DistDir: "./dist"}))
}
